# Generated by Django 3.1.12 on 2025-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210618_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, help_text='审核备注（例如驳回原因、修改建议等）', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(choices=[('pending', '未审核'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', help_text='任务审核状态：未审核/已通过/已驳回', max_length=16),
        ),
    ]
