title: 表格数据
type: community
group: 结构化数据解析
image: /static/templates/tabular-data.png
details: <h1>在表格中标注数据</h1>
config: '
<View>
    <Header value="包含 {键: 值} 对的表格"/>
    <Table name="table" value="$item"/>
</View>
'
