title: 正交回归
type: community
group: 排名和评分
image: /static/templates/pairwise-regression.png
details: <h1>选择两个项目同时出现的可能性</h1>
config: '
<View>
  <Header>请设置这些图像代表同一事物的可能性：</Header>
    <Image name="image1" value="$image1" />
    <Image name="image2" value="$image2" />
    <Rating name="rating" toName="image1,image2"/>
</View>
'
