title: PDF 分类
type: community
group: 结构化数据解析
image: /static/templates/pdf-classification.png
details: <h1>对 PDF 文档进行分类</h1>
config: '
<View>
    <Header value="请为本文评分"/>
  <Rating name="rating" toName="pdf" maxRating="10" icon="star" size="medium" />

  <Choices name="choices" choice="single-radio" toName="pdf" showInline="true">
    <Choice value="重要文章"/>
    <Choice value="小报文章"/>
  </Choices>
  <HyperText name="pdf" value="$pdf"/>
</View>
'
