title: PDF 分类
type: community
group: 结构化数据解析
image: /static/templates/pdf-classification.png
details: <h1>Classify PDF documents</h1>
config: '
<View>
    <Header value="Rate this article"/>
  <Rating name="rating" toName="pdf" maxRating="10" icon="star" size="medium" />

  <Choices name="choices" choice="single-radio" toName="pdf" showInline="true">
    <Choice value="Important article"/>
    <Choice value="Yellow press"/>
  </Choices>
  <HyperText name="pdf" value="$pdf"/>
</View>
'
