# Generated by Django 3.1.12 on 2026-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210517_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model_class',
            field=models.CharField(blank=True, default='', help_text='External model classification value (e.g. 101, 102) from the SSO platform dictionary', max_length=32, null=True, verbose_name='model class'),
        ),
    ]
