# Generated by Django 3.1.12 on 2026-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_model_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='export_split_enabled',
            field=models.BooleanField(default=False, help_text='Whether to split exported tasks into train/val/test folders', verbose_name='export split enabled'),
        ),
        migrations.AddField(
            model_name='project',
            name='export_split_ratios',
            field=models.JSONField(blank=True, default=dict, help_text='Ratios for train/val/test export split, e.g. {"train": 80, "val": 10, "test": 10}', null=True, verbose_name='export split ratios'),
        ),
    ]
