title: 活动识别
type: community
group: 时间序列分析
image: /static/templates/activity-recognition.png
details: <h1>基于传感器和 IMU 数据追踪并分类活动</h1>
config: '
<View>
    <!-- Control tag for region labels -->
    <TimeSeriesLabels name="label" toName="ts">
        <Label value="跑步" background="red"/>
        <Label value="步行" background="green"/>
        <Label value="飞行" background="blue"/>
        <Label value="游泳" background="#f6a"/>
        <Label value="骑行" background="#351"/>
    </TimeSeriesLabels>

    <!-- Object tag for time series data source -->
    <TimeSeries name="ts" valueType="url" value="$timeseriesUrl"
                sep=","
                timeColumn="time"
                timeFormat="%Y-%m-%d %H:%M:%S.%f"
                timeDisplayFormat="%Y-%m-%d"
                overviewChannels="velocity">

        <Channel column="velocity"
                 units="英里/小时"
                 displayFormat=",.1f"
                 strokeColor="#1f77b4"
                 legend="速度"/>

        <Channel column="acceleration"
                 units="英里/小时²"
                 displayFormat=",.1f"
                 strokeColor="#ff7f0e"
                 legend="加速度"/>
    </TimeSeries>
</View>
'
