# Generated by ChatGPT
from django.db import migrations, models


def set_owner_as_manager(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    User = apps.get_model('users', 'User')

    for org in Organization.objects.all():
        if not org.created_by_id:
            continue
        OrganizationMember.objects.filter(
            organization_id=org.id,
            user_id=org.created_by_id,
        ).update(role='manager')

    superuser_ids = list(User.objects.filter(is_superuser=True).values_list('id', flat=True))
    if superuser_ids:
        OrganizationMember.objects.filter(user_id__in=superuser_ids).update(role='manager')


def reset_owner_role(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    User = apps.get_model('users', 'User')

    for org in Organization.objects.all():
        if not org.created_by_id:
            continue
        OrganizationMember.objects.filter(
            organization_id=org.id,
            user_id=org.created_by_id,
        ).update(role='annotator')

    superuser_ids = list(User.objects.filter(is_superuser=True).values_list('id', flat=True))
    if superuser_ids:
        OrganizationMember.objects.filter(user_id__in=superuser_ids).update(role='annotator')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210310_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(
                choices=[('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('manager', 'Manager')],
                default='annotator',
                help_text='Organization membership role',
                max_length=32,
                verbose_name='role',
            ),
        ),
        migrations.RunPython(set_owner_as_manager, reset_owner_role),
    ]
