title: 视频分类
type: community
group: 视频
image: /static/templates/video-classification.png
details: <h1>对视频进行分类</h1>
config: '
<View>
  <HyperText name="video" value="$video"/>
  <Choices name="choice" toName="video" showInLine="true">
    <Choice value="模糊" />
    <Choice value="清晰" />
  </Choices>
</View>
'
